id: I43E1D471
source: https://library.bdrc.io
source_file: null
initial_creation_type: ocr
imported: '2020-03-21T16:50:31+00:00'
last_modified: '2022-06-08T12:47:50.170363+00:00'
parser: https://github.com/OpenPecha-dev/openpecha-toolkit/blob/231bba39dd1ba393320de82d4d08a604aabe80fc/openpecha/formatters/google_orc.py
source_metadata:
  id: bdr:W3CN5490
  title: ཧ་ལོ། བཀྲ་ཤིས་བདེ་ལེགས།
  author: ''
  access: http://purl.bdrc.io/admindata/AccessFairUse
  restrictedInChina: false
  base:
    7C5F:
      image_group_id: I3CN5492
      title: ''
      total_pages: 394
      order: 1
      base_file: 7C5F.txt
statistics: {}
quality: {}
copyright:
  status: Unknown
  notice: ''
  info_url: null
license: null
