id: P010330
initial_creation_type: ocr
created_at: 21/03/2020
last_modified_at: 2021-12-19 20:44:23.797189
source_metadata:
  id: bdr:W3CN5490
  title: ཧ་ལོ། བཀྲ་ཤིས་བདེ་ལེགས།
  author: ''
  volumes:
    0b3f17bb38264ddab5c5f299435d9142:
      image_group_id: I3CN5492
      title: ''
      volume_number: 1
      total_pages: 394
      base_file: v001.txt
  access: http://purl.bdrc.io/admindata/AccessFairUse
  restrictedInChina: false
