id: P010330
initial_creation_type: ocr
source_metadata:
  id: bdr:W3CN5490
  title: ཧ་ལོ། བཀྲ་ཤིས་བདེ་ལེགས།
  author: ''
  volumes:
    0b3f17bb38264ddab5c5f299435d9142:
      image_group_id: I3CN5492
      title: ''
      volume_number: 1
      total_pages: 394
